import { Resend } from "resend";

let _resend: Resend | null = null;
function getResend(): Resend {
  if (!_resend) {
    _resend = new Resend(process.env.RESEND_API_KEY);
  }
  return _resend;
}

export async function sendVideoEmail(
  to: string,
  videoUrl: string
): Promise<void> {
  await getResend().emails.send({
    from: "Donny <onboarding@resend.dev>",
    to,
    subject: "Your Property Video is Ready!",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #008dd8;">Your Property Video</h1>
        <p>Hi there,</p>
        <p>Your property video has been generated successfully!</p>
        <a href="${videoUrl}" target="_blank"
           style="display: inline-block; background: #008dd8; color: white; padding: 14px 28px;
                  text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0;">
          Watch Your Video
        </a>
        <p style="color: #666; font-size: 14px;">This link will be available for 7 days.</p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
        <p style="color: #999; font-size: 12px;">Generated by Donny - Property Video Generator</p>
      </div>
    `,
  });
}
